### ISSUE TITLE
error while "sudo npm install -g autopsy"

### ISSUE THREAD

**Issue by ashishsinghshah** [nearform/autopsy#10]
npm ERR! Error: No compatible version found: vboxmanage@'github:davidmarkclements/node-vboxmanage'
npm ERR! Valid install targets:
npm ERR! ["0.0.2","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.11","0.0.12","0.0.13","0.0.14","0.0.15"]
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at FSReqWrap.oncomplete (fs.js:111:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-573.18.1.el6.x86_64
npm ERR! command "/usr/local/n/versions/node/7.2.1/bin/node" "/usr/bin/npm" "install" "-g" "autopsy"
npm ERR! cwd /usr/local/bin
npm ERR! node -v v7.2.1
npm ERR! npm -v 1.3.6

**Comment by davidmarkclements** [comment]
is this just happening on Node 7?

**Comment by ashishsinghshah** [comment]
yes..."node -v v7.2.1"

**Comment by ashishsinghshah** [comment]
@davidmarkclements  let me know if you recommend to run this on specific versions of node and npm.
