### ISSUE TITLE
"Error: Encrypted private key detected, but no passphrase given" on "autopsy setup"

### ISSUE THREAD

**Issue by pararuk** [nearform/autopsy#11]

**Comment by Giovanini** [comment]
I'm also getting this error. Does anyone know how to solve this?

```
~ $ autopsy setup
Setting up smartos vm
Download Complete                 
Decompressing...
extracting assets/smartos.iso
extracting assets/smartos.ovf
smart os vm has been set up
SETUP TIME: 45752.480ms
booting vm to generate snapshot
vm up, waiting for ready state
No snapshot, first boot will take a while (up to 5 mins)
/usr/local/lib/node_modules/autopsy/node_modules/ssh-connect-prompt/node_modules/ssh2/lib/Connection.js:1154
        throw new Error('Encrypted private key detected, but no passphrase given');
        ^

Error: Encrypted private key detected, but no passphrase given
    at Connection.connect (/usr/local/lib/node_modules/autopsy/node_modules/ssh-connect-prompt/node_modules/ssh2/lib/Connection.js:1154:15)
    at next (/usr/local/lib/node_modules/autopsy/node_modules/ssh-connect-prompt/index.js:136:6)
    at onkey (/usr/local/lib/node_modules/autopsy/node_modules/ssh-connect-prompt/index.js:139:82)
    at connect (/usr/local/lib/node_modules/autopsy/node_modules/ssh-connect-prompt/index.js:143:3)
    at Object.ssh (/usr/local/lib/node_modules/autopsy/lib/connect.js:30:10)
    at check (/usr/local/lib/node_modules/autopsy/lib/start.js:43:29)
    at /usr/local/lib/node_modules/autopsy/lib/start.js:60:9
    at Object.callback (/usr/local/lib/node_modules/autopsy/node_modules/vboxmanage/lib/command.coffee:64:16)
    at next (/usr/local/lib/node_modules/autopsy/node_modules/vboxmanage/node_modules/async/lib/async.js:720:43)
    at /usr/local/lib/node_modules/autopsy/node_modules/vboxmanage/node_modules/async/lib/async.js:24:16
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/autopsy/node_modules/vboxmanage/lib/command.coffee:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
