### ISSUE TITLE
Unable to start (Error: cannot start smartos)

### ISSUE THREAD

**Issue by enVolt** [nearform/autopsy#12]
I already had VirtualBox in my system. When I run `autopsy start` command, it's giving following error - 

```
Error: cannot start smartos
    at /usr/local/lib/node_modules/autopsy/node_modules/vboxmanage/lib/instance.coffee:44:25
    at Object.callback (/usr/local/lib/node_modules/autopsy/node_modules/vboxmanage/lib/command.coffee:64:16)
    at next (/usr/local/lib/node_modules/autopsy/node_modules/vboxmanage/node_modules/async/lib/async.js:720:43)
    at /usr/local/lib/node_modules/autopsy/node_modules/vboxmanage/node_modules/async/lib/async.js:24:16
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/autopsy/node_modules/vboxmanage/lib/command.coffee:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

I'm on Mac OS X (Sierra 10.12.5 (16F73)) if that helps. Node version is v6.9.4.

Tried lot of googling couldn't find anything relevant.

**Comment by conordickinson** [comment]
I had the same problem, I fixed it by updating to the latest version of VirtualBox, then rerunning `autopsy setup` and removing the existing smartos VM.

**Comment by eugef** [comment]
I have the same error with latest VirtualBox 5.2.22 r126460 on macOS 10.11.6

Solution for me was to start VM manually with VirtualBox, enter it and login with root/root

Afterwards autopsy works
